server:
    port: 8081
    servlet:
      context-path: /api/v1

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true


logging:
  level:
    root: INFO
    com.project.paymentservice: DEBUG